### ISSUE TITLE
what is the /log endpoint for?

### ISSUE THREAD

**Issue by ionutale** [XenoverseUp/fractions#2]
are you stealing the user gains metrics?

**Comment by ionutale** [comment]
this one https://github.com/XenoverseUp/fractions/blob/main/server/server.mjs#L20

**Comment by XenoverseUp** [comment]
> are you stealing the user gains metrics?

Of course I am not. Because I don't have any friends writing on Medium, I cannot find all the bugs that can occur while using. So, I decided to create an endpoint which collects error logs and store whenever a user presses "Report" button, so that I can find the bugs and fix them. However, due to some issues, I didn't even integrated it to the final product. You can check out the rest of the code. I guess the report button related codes are in the .future file and not connected to the rest of the app.

**Comment by ionutale** [comment]
Yes i can confirm what you are saing.
